CREATE DATABASE Exercicio1_2;

USE Exercicio1_2;

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	NomeEmpresa VARCHAR(100) NOT NULL,
	CNPJ VARCHAR(14) NOT NULL
);

CREATE TABLE Marca
(
	IdMarca INT PRIMARY KEY IDENTITY,
	NomeMarca VARCHAR(20) NOT NULL,
);

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	NomeModelo VARCHAR(20) NOT NULL
);

CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	NomeCliente VARCHAR(50) NOT NULL,
	CPF VARCHAR(11)
);

CREATE TABLE Veiculos
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca),
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo),
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
	Placa VARCHAR(15) NOT NULL
);

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente),
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculos(IdVeiculo),
	DataRetirada DATE NOT NULL,
	DataDevolucao DATE NOT NULL
);