CREATE DATABASE Exercicio1_3;

CREATE TABLE Clinicas
(
	IdClinica INT PRIMARY KEY IDENTITY,
	NomeClinica VARCHAR(50) NOT NULL,
	CNPJ VARCHAR(16) NOT NULL,
	Endereco VARCHAR(255) NOT NULL
);

CREATE TABLE Dono
(
	IdDono INT PRIMARY KEY IDENTITY,
	NomeDono VARCHAR(60) NOT NULL,
	CPFDono VARCHAR (11) NOT NULL
);

CREATE TABLE TipoPet
(
	IdTipoPet INT PRIMARY KEY IDENTITY,
	NomeTipo VARCHAR(20) NOT NULL
);

CREATE TABLE RacaPet
(
	IdRacaPet INT PRIMARY KEY IDENTITY,
	NomeRaca VARCHAR(20) NOT NULL
);

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinicas(IdClinica),
	NomeVeterinario VARCHAR(50) NOT NULL,
	CRMV VARCHAR(4) NOT NULL
);

CREATE TABLE Pets
(
	IdPets INT PRIMARY KEY IDENTITY,
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet),
	IdRacaPet INT FOREIGN KEY REFERENCES RacaPet(IdRacaPet),
	NomePet VARCHAR(255) NOT NULL,
	DataNascimento VARCHAR(255) NOT NULL
);

CREATE TABLE Atendimento
(
	IdAtendimento INT PRIMARY KEY IDENTITY,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
	IdPets INT FOREIGN KEY REFERENCES Pets(IdPets),
	DataAtendimento VARCHAR(255) NOT NULL ,
	Descricao VARCHAR(255) NOT NULL
);
